<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_I agree with the terms of service and_f529a0</name>
   <tag></tag>
   <elementGuidId>ae5024bb-9048-4a5a-a224-672a42116c87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#termsofservice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='termsofservice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6972a70c-0d7a-40a5-8cb4-f125db06a943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>termsofservice</value>
      <webElementGuid>ae4b72df-ca0c-4fca-91a1-4cb6c0297dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>74434033-4497-4358-a51c-ff373dd94555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>termsofservice</value>
      <webElementGuid>74f7a1c2-b915-4022-9f77-84ec24457857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;termsofservice&quot;)</value>
      <webElementGuid>3c4d08af-9953-444f-bb4f-89e880de4638</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='termsofservice']</value>
      <webElementGuid>e526b98b-a383-4514-9f18-8fb471f00dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/input</value>
      <webElementGuid>e3142826-ab30-4a32-93cf-819d11ab3e9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'termsofservice' and @type = 'checkbox' and @name = 'termsofservice']</value>
      <webElementGuid>e9822cb5-bf10-441f-9c68-add6803d59e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
